#========================================
# Test profile settings (junit tests)
#========================================
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///junitdb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth:
      client:
        registration: {}
server:
  port: 8080
integration:
  citizen:
    base-url: localhost:8081/api/v2/citizen
logging:
  level:
    se.sundsvall.users.service.CitizenClient: DEBUG
    org.springframework.cloud.openfeign: DEBUG
