#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/user-management
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: users

  server:
    port: 8080
