#========================================
# Test profile settings (IT tests)
#========================================
logging:
  level:
    root: DEBUG
spring:
  datasource:
    url: jdbc:tc:mariadb:10.6.4:///
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
integration:
  citizen:
    base-url: http://localhost:${wiremock.server.port}
