#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/user_management
    username: user-manager
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: users

  server:
    port: 8080
